#Numpy

* Numpy is a general-purpose array-processing package.
* It provides a high-performance multidimensional array object, and tools for working with these arrays.
* It is the fundamental package for scientific computing with Python.
* Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
* In Numpy, number of dimensions of the array is called rank of the array.

In [2]:
# installation of numpy
!pip install numpy


In [3]:
#Importing NumPy
import numpy as np

In [4]:
#Creating Arrays
nj = np.array([1, 2, 3, 4,5])
print(nj)


[1 2 3 4 5]


In [5]:
js=np.array([44,54,57,27])
print(js)

[44 54 57 27]


In [7]:
#One-Dimensional
dk= np.array([1, 2, 3])
print(dk)

[1 2 3]


In [8]:
#Two-Dimensional
ya= np.array([[1, 2, 3], [4, 5, 6]])
print(ya)

[[1 2 3]
 [4 5 6]]


In [9]:
#Three-Dimensional
sa= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(sa)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
#Four-Dimensional
ik= np.array([[[[1,6,7], [2,4,3]], [[3,1,9], [4,6,4]]], [[[5,4,7], [6,9,1]], [[7,3,2], [8,7,2]]]])
print(ik)

[[[[1 6 7]
   [2 4 3]]

  [[3 1 9]
   [4 6 4]]]


 [[[5 4 7]
   [6 9 1]]

  [[7 3 2]
   [8 7 2]]]]


In [11]:
ik.shape

(2, 2, 2, 3)

In [12]:
ik.ndim

4

In [13]:
#Indexing
y= np.array([10, 20, 30, 40])
y[0]


10

In [14]:
a= np.array([1, 2, 3,4, 5, 6])
a[5]

6

In [15]:
#Slicing
lk=np.array([10, 20, 30, 40, 50,70,90])
lk[1:5]


array([20, 30, 40, 50])

In [16]:
#Slicing with step
hj=np.array([10, 20, 30, 40, 50,70,90])
hj[1:5:2]

array([20, 40])